# -*- coding: utf-8 -*-
"""Desafio Santander.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qlEzaxjvuHgO5XmVoPsqbZ9JKQXuM1P
"""

sdw2023_api_url = 'https://sdw-2023-prd.up.railway.app'

import pandas as pd

df = pd.read_csv('santander.csv')
user_ids = df['USERID'].tolist()
print(user_ids)

import requests
import json

def get_user(id):
  response=requests.get(f'{sdp2023_api_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [user for id in user_ids if (user := get_user(id))is not None]
print(json.dumps(users, indent=2))

!pip install openai

openai_api_key='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'

import openai
openai.api_key= openai_api_key

def generate_ai_news(user):
  completion = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    messages=[
      {
          "role": "system",
          "content": "Você é um especialista em indicar nomes de livros sobre programação, tecnologia e dados."
      },
      {
          "role": "user",
          "content": f"Crie uma mensagem interagindo com  {user['name']} indicando livros sobre dados, programação e tecnologia (maximo de 150 caracteres)"
      }
    ]
  )
  return completion.choices[0].message.content.strip('\"')

for user in users:
  news = generate_ai_news(user)
  print(news)
  user['news'].append({
      "icon": "https://digitalinnovationone.github.io/santander-dev-week-2023-api/icons/credit.svg",
      "description": news
  })

def update_user(user):
  response = requests.put(f"{sdp2023_api_url}/users/{user['id']}", json=user)
  return True if response.status_code == 200 else False

for user in users:
  success = update_user(user)
  print(f"User {user['name']} updated? {success}!")